### PR TITLE
Updated to XF 4.1.0.581479

### PR DESCRIPTION
**Pull request by garjitech**

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Thanks for the PR!

@garjitech were you hitting a problem with Xamarin.Forms 4.1.x? If so, what was the error message?

**Comment by ndastur** [comment]
@jonathanpeppers looking at the files it doesn't look like an incompatibility issue. After reading this PR I decide to update my NUnit project to XF 4 but I had been relucent to do so think that Mocks would work. As the README is quite vocal in matching versions I think this PR is reasonable?

**Comment by jonathanpeppers** [comment]
This PR would make the minimum required Xamarin.Forms at 4.1.0.581479. But if 3.6 continues to work, we don’t need a new release? It might be useful to make the test project target the newer versions, but I’ve had issues when Xamarin.Forms has mismatched versions within a solution.

Would you rather change this to reword the README? It should say 3.6 and up or something. Let me know what you think!

**Comment by jonathanpeppers** [comment]
I don't think this is needed. Closing for now, thanks!

**Pull request closed without merging**
