### PR TITLE
Add helper to access Uri sent to Device.OpenUri

### PR DESCRIPTION
**Pull request by Mark-RSK**
Added the helper class to allow checking the Uri sent to the Device.OpenUri method call. Also tracks the amount of time the method is called

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
This looks great, but I think we could fix up the API a little and just use an `Action<Uri>`.

```csharp
// Just put it on MockForms
public class MockForms
{
    //... Stuff here
    public static Action<Uri> OpenUriAction { get; set; }
}
```
`MockForms.Init` might also need to set this property to null.

Then you could test by doing something like:
```csharp
Uri expected = new Uri("something");
Uri actual = null;
MockForms.OpenUriAction = u => actual = u;
Device.OpenUri(expected);
Assert.AreEqual(expected, actual);
```
Using a callback, it has the flexibility you could increment a counter as well.

Does that make sense?

**Comment by Mark-RSK** [comment]
It does. I've made the changes locally. Should I rebase and reapply the pull request?

**Comment by jonathanpeppers** [comment]
I think you can just commit and do a push, you should see your new changes popup here on the PR.

**Comment by jonathanpeppers** [comment]
Looks good, I'll merge this and put out an update soon.

Thanks for the contribution.

**Comment by Mark-RSK** [comment]
All the changes should be in there now. I've modified the tests to match

**Comment by Mark-RSK** [comment]
No problem. Thanks for the library. I'll get a lot of use out of it :)

**Comment by jonathanpeppers** [comment]
I put out an update on NuGet, after changing one minor thing.

Let me know if there is something else missing, I have not been using Xamarin.Forms much lately since I've joined Microsoft and the Xamarin.Android team.

**Pull request merged**
