### PR TITLE
Feature/xamarin forms 5 0 support

### PR DESCRIPTION
**Pull request by epsmae**

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Does anything actually break with Xamarin.Forms 5.0?

If none of the interfaces change, we might not actually need an update? You could just use the Xamarin.Forms.Mocks 4.7.x packages.

**Comment by epsmae** [comment]
MasterDetailPage was renamed to FlyoutPage.

https://docs.microsoft.com/en-us/xamarin/xamarin-forms/release-notes/5.0/5.0.0

**Comment by jonathanpeppers** [comment]
Can you share an example of a test that was broken?

You should be able to use Xamarin.Forms 5.x and Xamarin.Forms.Mocks 4.7.x together.

**Comment by epsmae** [comment]
You are right 👍

**Pull request closed without merging**
