### PR TITLE
updates for Xamarin Forms 3.0

### LINKED ISSUE #27: Mocks break with Xamarin Forms 3.0
# Description 

Xamarin Forms 3.0 present several breaking changes both for consuming apps and internal testing.

## Consuming App Breaks

- IsolatedStorageFile has been updated for netstandard2.0 to use System.IO FileMode, FileAccess, & FileShare. 

## Internal Tests

- WinRT has been removed from Device
- Windows platform has been removed from Device
- Tizen has been added to Device
- macOS has been added to Device
- UWP has been added to Device
- WPF has been added to Device

### PR DESCRIPTION
**Pull request by dansiegel**
Fixes #27

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
This looks like great work thanks! It might be this weekend before I can review, so bear with!

**Comment by jonathanpeppers** [comment]
This looks good, I'm going to merge, but I'll probably make the 3.x version of Xamarin.Forms.Mocks a prerelease until Xamarin.Forms 3.0 hits stable.

**Comment by jonathanpeppers** [comment]
@dansiegel I pushed a prerelease to NuGet: https://www.nuget.org/packages/Xamarin.Forms.Mocks/3.0.0.1-pre2

**Comment by dansiegel** [comment]
Pretty sure NuGet won’t allow a non prerelease with a prerelease dependency. Either way makes more sense to me that way anyway. Thanks for getting this up so quick!

**Comment by wsloth** [comment]
Fix works very well. When will this be released as a non-prerelease package update?

**Comment by wsloth** [comment]
It's at 2.5.4 still on NuGet. I am temporarily using the prerelease version in my project right now.

**Comment by jonathanpeppers** [comment]
@wsloth the "prerelease" one should be fine to use, NuGet just makes you mark your package prerelease if you have a dependency on prerelease.

It may be fine to use Xamarin.Forms 3.0 stable + Xamarin.Forms.Mocks prerelease until I get an update up.

**Comment by wsloth** [comment]
Oh, I see, thank you for the explanation. I'll see the "stable" version pop up whenever the dependencies are all stable.

Thank you for the work on this package!

**Comment by jonathanpeppers** [comment]
@wsloth I just pushed version 3.0.0.2 of Xamarin.Forms.Mocks.

Let me know if it works for you!

**Pull request merged**
